<?php


namespace UserObject\Bank;

class Bank extends \MainClass
{
    protected function execute()
    {

        parent::execute(); // TODO: Change the autogenerated stub
    }

    protected function bankHandler()
    {
        if (isset($_POST['form'])) {
            /* Likely wanting to manipulate money*/
        } elseif (isset($_GET['sendtil'])) {
            /* Wanting to send money to someone specific */
        }
    }
}
