<?php


/**
 * Class GameInfo
 */
class GameInfo extends MainClass
{
    public function execute()
    {
        if ($write = $this->canUseFunction(accesstable: ['ADM'])) {
            $this->out .= $write;
        } else {
            $this->readyGameInfo();
        }
        parent::execute(); // TODO: Change the autogenerated stub
    }
    public function readyGameInfo()
    {
        $this->out .= <<<END
<p>PHP versjon: {PHPVERSION}</p>
<p>Nginx versjon: {NGINXVERSION}</p>
<p>Aktive PHP extensions:</p>
<ul>
{PHPEXTENSIONS}
</ul>
END;
        $ext = '';
        foreach (get_loaded_extensions() as $exts) {
            $ext .= '<li>' . $exts . '</li>';
        }
        $this->out = str_replace(
            ['{PHPVERSION}', '{NGINXVERSION}', '{PHPEXTENSIONS}'],
            [phpversion(), $_SERVER['SERVER_SOFTWARE'], $ext],
            $this->out
        );
    }
}
