<?php


class News extends MainClass
{

    public function __construct(User $user, PDO $database, string $title = "ReplaceMe")
    {
        parent::__construct($user, $database, $title);
    }

    protected function execute()
    {
        parent::execute(); // TODO: Change the autogenerated stub
    }

    protected function loadPage()
    {
        parent::loadPage(); // TODO: Change the autogenerated stub
    }
}
